site:
  title: stickland-Navigation 
  description: 我的个人网络导航
  author: stickland
  favicon: favicon.ico
  logo_text: 导航站
fonts:
  title:
    family: Poppins
    weight: 600
    source: google
  subtitle:
    family: Quicksand
    weight: 500
    source: google
  body:
    family: Noto Sans SC
    weight: 400
    source: google
profile:
  title: Hello,
  subtitle: Welcome to My Navigation
  description: 导航菜单
navigation:
  - name: 首页
    icon: fas fa-home
    id: home
    active: true
  - name: 项目
    icon: fas fa-project-diagram
    id: projects
  - name: 文章
    icon: fas fa-book
    id: articles
  - name: 朋友
    icon: fas fa-users
    id: friends
  - name: 书签
    icon: fas fa-bookmark
    id: bookmarks
social:
  - name: Blog
    url: https://blog.stickland.top
    icon: fab fa-blog
categories:
  - name: MY-WEBSITE
    icon: fas fa-star
    sites:
      - name: AI-Chat
        url: https://chat.stickland.top
        icon: fa-solid fa-message
        description: ai公益站,内置多种付费顶级大模型
      - name: AI-image
        url: https://image.stickland.top
        icon: fa-solid fa-images
        description: ai文生图公益站
      - name: AI深度研究
        url: https://deep.stickland.top
        icon: fa-solid fa-magnifying-glass
        description: 深度研究，一键导出研究报告（完善中）
      - name: 取件码-剪切板-文件箱
        url: https://file.stickland.top
        icon: fa-solid fa-file
        description: 支持6位数取件码传文字和文件，阅后即焚。
      - name: 一键小网页生成
        url: https://page.stickland.top
        icon: fa-solid fa-file-lines
        description: 简单编辑生成长久访问的页面(->联系我授权)
      - name: 我的博客
        url: https://blog.stickland.top
        icon: fa-solid fa-eye
        description: 点击催我更新博客（咕咕）
  - name: 学习资源
    icon: fas fa-graduation-cap
    sites:
      - name: 哔哩哔哩
        url: https://www.bilibili.com
        icon: fas fa-play-circle
        description: 视频学习平台
      - name: 知乎
        url: https://www.zhihu.com
        icon: fas fa-question-circle
        description: 问答社区
      - name: 掘金
        url: https://juejin.cn
        icon: fas fa-book
        description: 高质量技术社区
      - name: LeetCode
        url: https://leetcode.cn
        icon: fas fa-code
        description: 算法刷题平台
  - name: 开发工具
    icon: fas fa-tools
    sites:
      - name: VS Code
        url: https://code.visualstudio.com
        icon: fas fa-code
        description: 强大的代码编辑器
      - name: Postman
        url: https://www.postman.com
        icon: fas fa-paper-plane
        description: API调试工具
      - name: Git
        url: https://git-scm.com
        icon: fab fa-git-alt
        description: 版本控制工具
      - name: Docker
        url: https://www.docker.com
        icon: fab fa-docker
        description: 容器化平台
  - name: 设计资源
    icon: fas fa-palette
    sites:
      - name: Figma
        url: https://www.figma.com
        icon: fab fa-figma
        description: 在线设计工具
      - name: Dribbble
        url: https://dribbble.com
        icon: fab fa-dribbble
        description: 设计师社区
      - name: Behance
        url: https://www.behance.net
        icon: fab fa-behance
        description: 创意设计平台
      - name: IconFont
        url: https://www.iconfont.cn
        icon: fas fa-icons
        description: 图标资源库
  - name: 在线工具
    icon: fas fa-wrench
    sites:
      - name: JSON Editor
        url: https://jsoneditoronline.org
        icon: fas fa-code-branch
        description: JSON在线编辑器
      - name: Can I Use
        url: https://caniuse.com
        icon: fas fa-browser
        description: 浏览器兼容性查询
      - name: TinyPNG
        url: https://tinypng.com
        icon: fas fa-compress
        description: 图片压缩工具
      - name: Carbon
        url: https://carbon.now.sh
        icon: fas fa-code
        description: 代码图片生成器
