site:
  title: stickland-Navigation 
  description: 我的个人网络导航
  author: stickland
  favicon: favicon.ico
  logo_text: stickland
fonts:
  title:
    family: Poppins
    weight: 600
    source: google
  subtitle:
    family: Quicksand
    weight: 500
    source: google
  body:
    family: Noto Sans SC
    weight: 400
    source: google
profile:
  title: Hello,
  subtitle: Welcome to My Navigation
  description: ↓↓↓下面是我的个人网站↓↓↓
navigation:
  - name: 首页
    icon: fas fa-home
    id: home
    active: true
  - name: 项目
    icon: fas fa-project-diagram
    id: projects
  - name: 文章
    icon: fas fa-book
    id: articles
  - name: 朋友
    icon: fas fa-users
    id: friends
  - name: 书签
    icon: fas fa-bookmark
    id: bookmarks
social:
  - name: Blog
    url: https://blog.stickland.top
    icon: fa-solid fa-braille
categories:
  - name: MY-WEBSITE
    icon: fas fa-star
    sites:
      - name: AI-Chat
        url: https://chat.stickland.top
        icon: fa-solid fa-message
        description: ai公益站,内置多种付费顶级大模型
      - name: AI-image
        url: https://image.stickland.top
        icon: fa-solid fa-images
        description: ai文生图公益站
      - name: AI深度研究
        url: https://deep.stickland.top
        icon: fa-solid fa-magnifying-glass
        description: 深度研究，一键导出研究报告（完善中）
      - name: 取件码-剪切板-文件箱
        url: https://file.stickland.top
        icon: fa-solid fa-file
        description: 支持6位数取件码传文字和文件，阅后即焚。
      - name: 一键小网页生成
        url: https://page.stickland.top
        icon: fa-solid fa-file-lines
        description: 简单编辑生成长久访问的页面(->联系我授权)
      - name: 我的博客
        url: https://blog.stickland.top
        icon: fa-solid fa-eye
        description: 点击催我更新博客（咕咕）
      - name: 我的导航站
        url: https://guide.stickland.top
        icon: fa-solid fa-location-pin
        description: 本站在此！
  - name: 学习资源
    icon: fas fa-graduation-cap
    sites:
      - name: 哔哩哔哩
        url: https://www.bilibili.com
        icon: fas fa-play-circle
        description: 视频学习平台
      - name: 知乎
        url: https://www.zhihu.com
        icon: fas fa-question-circle
        description: 问答社区
      - name: 掘金
        url: https://juejin.cn
        icon: fas fa-book
        description: 高质量技术社区
      - name: LeetCode
        url: https://leetcode.cn
        icon: fas fa-code
        description: 算法刷题平台
  - name: 开发工具
    icon: fas fa-tools
    sites:
      - name: VS Code
        url: https://code.visualstudio.com
        icon: fas fa-code
        description: 强大的代码编辑器
      - name: Postman
        url: https://www.postman.com
        icon: fas fa-paper-plane
        description: API调试工具
      - name: Git
        url: https://git-scm.com
        icon: fab fa-git-alt
        description: 版本控制工具
      - name: Docker
        url: https://www.docker.com
        icon: fab fa-docker
        description: 容器化平台
  - name: 设计资源
    icon: fas fa-palette
    sites:
      - name: Figma
        url: https://www.figma.com
        icon: fab fa-figma
        description: 在线设计工具
      - name: Dribbble
        url: https://dribbble.com
        icon: fab fa-dribbble
        description: 设计师社区
      - name: Behance
        url: https://www.behance.net
        icon: fab fa-behance
        description: 创意设计平台
      - name: IconFont
        url: https://www.iconfont.cn
        icon: fas fa-icons
        description: 图标资源库
  - name: 在线工具
    icon: fas fa-wrench
    sites:
      - name: JSON Editor
        url: https://jsoneditoronline.org
        icon: fas fa-code-branch
        description: JSON在线编辑器
      - name: Can I Use
        url: https://caniuse.com
        icon: fas fa-browser
        description: 浏览器兼容性查询
      - name: TinyPNG
        url: https://tinypng.com
        icon: fas fa-compress
        description: 图片压缩工具
      - name: Carbon
        url: https://carbon.now.sh
        icon: fas fa-code
        description: 代码图片生成器
projects:
  title: 我的项目
  subtitle: 这里展示了我的一些个人项目和开源贡献
  categories:
    - name: 个人项目
      icon: fas fa-code
      sites:
        - name: AI文生图前端
          icon: fas fa-compass
          description: 练手作，过于粗糙，别看
          url: "https://github.com/stickland1101/Ai_Image_Generator_Webpage"

articles:
  title: 技术文章
  subtitle: 分享我的技术文章和学习笔记
  categories:
    - name: 最新文章
      icon: fas fa-pen
      sites:
        - name: 还没有更新呢
          icon: fab fa-vuejs
          description: 再等等
          url: "#"

    - name: 学习笔记
      icon: fas fa-book
      sites:
        - name: 还没有更新呢
          icon: fab fa-react
          description: 再等等
          url: "#"

    - name: 源码解析
      icon: fas fa-code
      sites:
        - name: Vue源码解析
          icon: fab fa-vuejs
          description: Vue.js核心原理解析
          url: "#"
        - name: React原理
          icon: fab fa-react
          description: React核心机制解析
          url: "#"
friends:
  title: 友情链接
  subtitle: 优秀的博主和朋友们
  categories:
    - name: 技术博主
      icon: fas fa-user-friends
      sites:
        - name: 欢迎添加我的友链
          icon: fas fa-code
          description: 互加互加！
          url: "#"
 
    - name: 技术社区
      icon: fas fa-laptop-code
      sites:
        - name: GitHub
          icon: fab fa-github
          description: 开源代码托管平台
          url: https://github.com
        - name: Stack Overflow
          icon: fab fa-stack-overflow
          description: 程序员问答社区
          url: https://stackoverflow.com
        - name: 掘金
          icon: fas fa-book
          description: 高质量技术社区
          url: https://juejin.cn
        - name: V2EX
          icon: fas fa-comments
          description: 创意工作者社区
          url: https://v2ex.com
    - name: 休闲娱乐
      icon: fas fa-coffee
      sites:
        - name: 哔哩哔哩
          icon: fas fa-play-circle
          description: 视频弹幕网站
          url: https://www.bilibili.com
        - name: 知乎
          icon: fas fa-question-circle
          description: 问答社区
          url: https://www.zhihu.com
        - name: 豆瓣
          icon: fas fa-film
          description: 文艺生活社区
          url: https://www.douban.com
        - name: 网易云音乐
          icon: fas fa-music
          description: 音乐平台
          url: https://music.163.com
